apiVersion: v2
appVersion: "4.3.9" # legacy stable version
description: A Helm chart for qBittorrent with integrated VPN
name: qbittorrent
version: 0.1.1
kubeVersion: ">=1.19.0-0"
keywords:
  - qbittorrent
  - torrent
  - vpn
home: https://www.qbittorrent.org/
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/hotio/qbittorrent
  - https://github.com/kriegalex/k8s-charts
type: application
