apiVersion: v2
name: radarr
description: A Radarr Helm chart for Kubernetes

type: application

version: 1.5.0

# renovate: image=hotio/radarr
appVersion: "release-5.8.3.8933"

icon: https://avatars.githubusercontent.com/u/25025331
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bumped radarr version to release-5.8.3.8933
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://gitlab.com/alexander-chernov/helm/radarr
